/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.JDialog.ScreenCRUDLibrary.ScreenChooseBooks;

import Connection.database.connection.SQLiteConnector;
import Controller.BookController;
import Model.Dao.IDao;
import Model.Dao.IDaoBookDatabase;
import Model.entitites.Book;
import View.JTableModel.TMBook;
import java.sql.SQLException;

/**
 *
 * @author jc
 */
public class JDlgChooseBook extends javax.swing.JDialog {

    private TMBook tm_book;
    private BookController book_controller;
    private Book book;
    /**
     * Creates new form JDlgChooseBook
     */
    public JDlgChooseBook(java.awt.Frame parent, boolean modal, Book book) throws SQLException {
        super(parent, modal);
        initComponents();

        //Data Base Book
        SQLiteConnector sql_connector = new SQLiteConnector("Biblioteca.db");
        IDao bookDao = new IDaoBookDatabase(sql_connector.getConnection());
        
        book_controller = new BookController(bookDao);
        
        this.Update_Table();
        
        this.book = book;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbnCRUDBook = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCod_book = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdBook = new javax.swing.JTable();
        btnAddLivro = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbnCRUDBook.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbnCRUDBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbnCRUDBook.setText("Escolha um Livro");

        jLabel1.setText("COD_Livro:");

        txtCod_book.setToolTipText("");
        txtCod_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_bookActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        grdBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "COD_Livro", "Nome", "Author"
            }
        ));
        grdBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdBook);

        btnAddLivro.setBackground(new java.awt.Color(51, 153, 0));
        btnAddLivro.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnAddLivro.setForeground(new java.awt.Color(0, 0, 0));
        btnAddLivro.setText("Adicionar Livro");
        btnAddLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLivroActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(153, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbnCRUDBook, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnAddLivro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCod_book, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbnCRUDBook, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod_book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLivro)
                    .addComponent(btnCancelar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCod_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_bookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_bookActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAddLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLivroActionPerformed
        this.book = getObjetoSelecionadoNaGrid();
        this.dispose();
    }//GEN-LAST:event_btnAddLivroActionPerformed

    private void grdBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdBookMouseClicked
        this.book = getObjetoSelecionadoNaGrid();
        this.dispose();
    }//GEN-LAST:event_grdBookMouseClicked
    
    public void Update_Table(){
        tm_book = new TMBook(book_controller.listBooks());
        grdBook.setModel(tm_book);
    }
    
    public Book getSelectedBook() {
        return this.book;
    }
    
    public Book getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdBook.getSelectedRow();
        int columnSelecionada = grdBook.getColumnCount();

        if (linhaSelecionada >= 0) {
            TMBook tmCadBook = (TMBook) grdBook.getModel();

//          Book book = (Book) 
            return tmCadBook.getObjectBook(linhaSelecionada);
        }

        return null;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLivro;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTable grdBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbnCRUDBook;
    private javax.swing.JTextField txtCod_book;
    // End of variables declaration//GEN-END:variables
}
